apiVersion: v1
kind: Service
metadata:
  name: servicenp
  labels:
    podname: nginxpod1
  namespace: test
spec:
  selector: 
    name: nginxpod1
  type: NodePort
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
   
