apiVersion: v1
kind: Service
metadata:
  name: service1
  labels:
    podname: nginxpod1
  namespace: test
spec:
  selector: 
    name: nginxpod1
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
   
